### ISSUE TITLE
React 18 – Children props.

### ISSUE THREAD

**Issue by Danielto1404** [Muzikanto/react-near#1]
The following code provides an error

```js
const App: React.FC<AppProps> = ({
    Component,
    pageProps
}) => (
    <NearProvider environment={NearEnvironment.MainNet}>
        <Component {...pageProps}/>
    </NearProvider>
)
```

Error is:
`
TS2322: Type '{ children: Element; environment: NearEnvironment.MainNet; }' is not assignable to type 'IntrinsicAttributes & Partial<ConnectConfig> & { environment?: NearEnvironment | undefined; }'.   Property 'children' does not exist on type 'IntrinsicAttributes & Partial<ConnectConfig> & { environment?: NearEnvironment | undefined; }'.
`

In `React 18+` you should manually type Component which takes `children` as props.

See the StackOverflow discussion [here](https://stackoverflow.com/questions/71788254/react-18-typescript-children-fc)

**Comment by Muzikanto** [comment]
Thank you, I've made the changes.
